// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/quotations/get": {
            "get": {
                "description": "Возвращает котировку по идентификатору обновления",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quotations"
                ],
                "summary": "Получить котировку по идентификатору",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор обновления",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.quotationResponse"
                        }
                    }
                }
            }
        },
        "/quotations/latest": {
            "get": {
                "description": "Возвращает последнее валидное значение котировки",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quotations"
                ],
                "summary": "Получить последнее значение котировки",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Базовая валюта",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Котируемая валюта",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.quotationResponse"
                        }
                    }
                }
            }
        },
        "/quotations/update": {
            "get": {
                "description": "Создаёт новый запрос на обновление котировки",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quotations"
                ],
                "summary": "Обновить котировку",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Базовая валюта",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Котируемая валюта",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.quotationResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "rate": {
                    "type": "number"
                },
                "update_time": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "REST API test service for BWG",
	Description:      "API Сервер для управления котировками",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
